### PR TITLE
increase versions to go to next version with all of them

### PR DESCRIPTION
**Pull request by ElectricMaxxx**
This PR enables me to update sandbox to use the current versions (dev-master) of cmf bundles.

### CODE REVIEW

**Comment by ElectricMaxxx** [comment]
travis hook is broken, build was green.

**Comment by dbu** [comment]
doctrine-bundle does not support obsolete symfony versions 3.0-3.2 anymore, only 2.8, ^3.3 and ^4.0, see https://github.com/doctrine/DoctrinePHPCRBundle/blob/master/composer.json#L22

i thin we should do the same here. and while we are at it, we could also clean up the travis file to follow the [best practices](https://symfony.com/doc/current/bundles/best_practices.html#continuous-integration)

**Comment by ElectricMaxxx** [comment]
@dbu what do you think now?

**Comment by dbu** [comment]
thanks!

**Pull request merged**
