### PR TITLE
Menu 2.0

### PR DESCRIPTION
**Pull request by dbu**

### CODE REVIEW

**Comment by WouterJ** [comment]
We can decide to do 2 things here. All bundles required by this package support both CmfMenuBundle 1 and 2. We can require CmfMenuBundle 2 (current state), meaning we force everyone to use KnpMenuBundle 2 (which I believe is a good thing) or we change it to `1.2.*|2.*`, allowing to install both major versions of the bundle.

**Comment by dbu** [comment]
is sonata now able to live with knp menu 2.0? if it is, i am ok with
going 2.0

**Comment by WouterJ** [comment]
SonataAdminbundle 2.4 requires KnpMenu 2 and 2.3 supports both

**Comment by dbu** [comment]
excellent!

**Pull request merged**
